#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
MMSegTrain = ROOT / "third_party" / "mmsegmentation" / "tools" / "train.py"
BASE_CFG = ROOT / "configs" / "tp_dataset" / "segformer_b2_tp_skel_clDice_v2_4090_bs4.py"
TARGET_ITERS = 10000
ACCEPT_EXISTING_PARTIAL = {"core_none", "core_main_only"}

CASE_DEFS: Dict[str, Tuple[float, float]] = {
    "core_none": (0.0, 0.0),
    "core_main_only": (0.1, 0.0),
    "core_aux_only": (0.0, 0.1),
    "core_both": (0.1, 0.1),
    "w_0p05": (0.05, 0.05),
    "w_0p10": (0.10, 0.10),
    "w_0p20": (0.20, 0.20),
    "w_0p30": (0.30, 0.30),
}


def write_cfg(cfg_path: Path, work_dir: str, decode_cldice: float, aux_cldice: float) -> None:
    text = f"""_base_ = ['../segformer_b2_tp_skel_clDice_v2_4090_bs4.py']

# Auto-generated by tools/run_ablation_missing_only.py
work_dir = '{work_dir}'

model = dict(
    decode_head=dict(
        loss_decode=[
            dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            dict(type='DiceLoss', use_sigmoid=False, loss_weight=0.5),
            dict(type='SoftCLDiceLoss', foreground_index=1, iterations=10, loss_weight={decode_cldice}),
        ],
    ),
    auxiliary_head=dict(
        loss_bce=dict(type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.5),
        loss_dice=dict(type='DiceLoss', use_sigmoid=True, loss_weight=0.5),
        loss_cldice=dict(type='SoftCLDiceLoss', foreground_index=0, iterations=10, loss_weight={aux_cldice}),
    ),
)

default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        by_epoch=False,
        interval=500,
        save_last=True,
        max_keep_ckpts=20,
        save_best='mIoU',
        rule='greater',
        out_dir='{work_dir}/ckpt',
    ),
    logger=dict(type='LoggerHook', interval=50),
)

train_cfg = dict(type='IterBasedTrainLoop', max_iters=10000, val_interval=500)
"""
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(text, encoding="utf-8")


def parse_best_metrics(log_path: Path) -> Dict[str, str]:
    if not log_path.exists():
        return {"status": "no_log"}

    text = log_path.read_text(encoding="utf-8", errors="ignore")
    best_m = re.findall(r"best checkpoint with\s*([0-9.]+)\s*mIoU at\s*([0-9]+)\s*iter", text)
    if not best_m:
        return {"status": "no_best_found"}

    best_miou, best_iter = best_m[-1]
    best_marker = f"best checkpoint with {best_miou} mIoU at {best_iter} iter"
    marker_pos = text.rfind(best_marker)

    val_pat = re.compile(
        r"Iter\(val\) \[281/281\]\s+aAcc:\s*([0-9.]+)\s+mIoU:\s*([0-9.]+)\s+mAcc:\s*([0-9.]+)\s+mDice:\s*([0-9.]+)\s+mFscore:\s*([0-9.]+)\s+mPrecision:\s*([0-9.]+)\s+mRecall:\s*([0-9.]+)",
        re.MULTILINE,
    )
    val_matches = list(val_pat.finditer(text[:marker_pos] if marker_pos > 0 else text))

    row_pat = re.compile(
        r"\|\s*tactile_paving\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|"
    )
    rows = list(row_pat.finditer(text[:marker_pos] if marker_pos > 0 else text))

    out: Dict[str, str] = {
        "status": "ok",
        "best_iter": best_iter,
        "best_mIoU": best_miou,
    }

    if val_matches:
        aAcc, mIoU, mAcc, mDice, mFscore, mPrecision, mRecall = val_matches[-1].groups()
        out.update(
            {
                "aAcc": aAcc,
                "mIoU": mIoU,
                "mAcc": mAcc,
                "mDice": mDice,
                "mFscore": mFscore,
                "mPrecision": mPrecision,
                "mRecall": mRecall,
            }
        )

    if rows:
        tactile_iou, tactile_acc, tactile_dice, tactile_fscore, tactile_precision, tactile_recall = rows[-1].groups()
        out.update(
            {
                "tactile_iou": tactile_iou,
                "tactile_acc": tactile_acc,
                "tactile_dice": tactile_dice,
                "tactile_fscore": tactile_fscore,
                "tactile_precision": tactile_precision,
                "tactile_recall": tactile_recall,
            }
        )

    return out


def parse_best_from_scalars(work_dir: Path) -> Dict[str, str]:
    scalars = sorted(work_dir.glob("*/vis_data/scalars.json"))
    best_val = -1.0
    best_step = ""
    best_row: Dict[str, str] = {}

    for f in scalars:
        for line in f.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            if "mIoU" in obj and "step" in obj:
                v = float(obj["mIoU"])
                if v > best_val:
                    best_val = v
                    best_step = str(int(obj["step"]))
                    best_row = {
                        "aAcc": f"{obj.get('aAcc', '')}",
                        "mIoU": f"{obj.get('mIoU', '')}",
                        "mAcc": f"{obj.get('mAcc', '')}",
                        "mDice": f"{obj.get('mDice', '')}",
                        "mFscore": f"{obj.get('mFscore', '')}",
                        "mPrecision": f"{obj.get('mPrecision', '')}",
                        "mRecall": f"{obj.get('mRecall', '')}",
                    }

    if best_val < 0:
        return {"status": "no_scalar_best"}

    out = {
        "status": "ok_from_scalars",
        "best_iter": best_step,
        "best_mIoU": f"{best_val:.4f}",
    }
    out.update(best_row)
    return out


def max_iter_in_ckpt(work_dir: Path) -> int:
    max_iter = 0
    for p in work_dir.glob("ckpt/**/iter_*.pth"):
        m = re.search(r"iter_(\d+)\.pth$", str(p))
        if not m:
            continue
        it = int(m.group(1))
        if it > max_iter:
            max_iter = it
    return max_iter


def is_case_complete(work_dir: Path) -> bool:
    return max_iter_in_ckpt(work_dir) >= TARGET_ITERS


def find_existing_record(case: str, work_dir: Path) -> Dict[str, str]:
    # Keep previously accepted existing cases to avoid unnecessary reruns.
    if case in ACCEPT_EXISTING_PARTIAL:
        rec = parse_best_from_scalars(work_dir)
        if rec.get("status", "").startswith("ok"):
            return rec

    # Only treat as completed if this case has reached full target iterations.
    if not is_case_complete(work_dir):
        return {}

    rec = parse_best_from_scalars(work_dir)
    if rec.get("status", "").startswith("ok"):
        return rec
    return {
        "status": "ok_ckpt_only",
        "best_iter": "",
        "best_mIoU": "",
    }


def run_one(cfg: Path, work_dir: Path, log_path: Path, env: Dict[str, str]) -> int:
    work_dir.mkdir(parents=True, exist_ok=True)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "python",
        "-u",
        str(MMSegTrain),
        str(cfg),
        "--work-dir",
        str(work_dir),
    ]
    print(f"[RUN] {' '.join(cmd)}")
    with log_path.open("w", encoding="utf-8") as f:
        proc = subprocess.Popen(cmd, cwd=str(ROOT), env=env, stdout=f, stderr=subprocess.STDOUT)
        return proc.wait()


def write_rows(csv_path: Path, rows: List[Dict[str, str]]) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = sorted({k for r in rows for k in r.keys()})
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def read_rows(csv_path: Path) -> List[Dict[str, str]]:
    if not csv_path.exists():
        return []
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return [dict(r) for r in reader]


def merge_row_map(row_map: Dict[str, Dict[str, str]], rows: List[Dict[str, str]]) -> None:
    for r in rows:
        name = (r.get("name") or "").strip()
        if not name:
            continue
        if name not in row_map:
            row_map[name] = dict(r)
            continue
        # Fill missing keys from legacy rows, but keep newer values if already present.
        for k, v in r.items():
            if row_map[name].get(k, "") in ("", None) and v not in ("", None):
                row_map[name][k] = v


def sort_rows_for_output(rows: List[Dict[str, str]]) -> List[Dict[str, str]]:
    order = {name: i for i, name in enumerate(CASE_DEFS.keys())}
    return sorted(rows, key=lambda r: (order.get(r.get("name", ""), 999), r.get("name", "")))


def main() -> None:
    parser = argparse.ArgumentParser(description="Run only missing ablation cases and build a comparison table.")
    parser.add_argument(
        "--cases",
        default=",".join(CASE_DEFS.keys()),
        help="Comma-separated case names. Default: all 8 cases.",
    )
    parser.add_argument(
        "--output-csv",
        default="work_dirs/ablation/ablation_results_completed.csv",
        help="Final comparison table path.",
    )
    args = parser.parse_args()

    if not BASE_CFG.exists():
        raise FileNotFoundError(f"Missing base cfg: {BASE_CFG}")

    selected = [c.strip() for c in args.cases.split(",") if c.strip()]
    for c in selected:
        if c not in CASE_DEFS:
            raise ValueError(f"Unknown case: {c}")

    cfg_dir = ROOT / "configs" / "tp_dataset" / "ablation_generated"
    log_dir = ROOT / "logs" / "ablation"
    out_csv = ROOT / args.output_csv

    # Seed from existing summaries so reruns never wipe previous cases.
    seed_csvs = [
        out_csv,
        ROOT / "work_dirs" / "ablation" / "ablation_results_fullrerun_20260329.csv",
        ROOT / "work_dirs" / "ablation" / "ablation_results.csv",
    ]
    row_map: Dict[str, Dict[str, str]] = {}
    for s in seed_csvs:
        merge_row_map(row_map, read_rows(s))

    env = os.environ.copy()
    env["PYTHONPATH"] = f"{ROOT}:{ROOT / 'third_party' / 'mmsegmentation'}:{env.get('PYTHONPATH', '')}"

    for name in selected:
        d_w, a_w = CASE_DEFS[name]
        work_dir = ROOT / "work_dirs" / "ablation" / name
        cfg = cfg_dir / f"{name}.py"

        rec: Dict[str, str] = dict(row_map.get(name, {}))
        rec.update({
            "name": name,
            "decode_cldice_weight": f"{d_w}",
            "aux_cldice_weight": f"{a_w}",
            "cfg": str(cfg.relative_to(ROOT)),
            "work_dir": str(work_dir.relative_to(ROOT)),
        })

        existing = find_existing_record(name, work_dir)
        if existing:
            rec.update(existing)
            rec["train_status"] = "skipped_existing"
            rec.setdefault("exit_code", "")
            rec.setdefault("log", "")
            row_map[name] = rec
            print(f"[SKIP] {name}: existing artifacts detected, no rerun")
            write_rows(out_csv, sort_rows_for_output(list(row_map.values())))
            continue

        write_cfg(cfg, str(work_dir.relative_to(ROOT)), d_w, a_w)
        log_path = log_dir / f"train_{name}_{time.strftime('%Y%m%d_%H%M%S')}.log"

        rc = run_one(cfg, work_dir, log_path, env)
        rec["train_status"] = "ok" if rc == 0 else "failed"
        rec["exit_code"] = str(rc)
        rec["log"] = str(log_path.relative_to(ROOT))

        parsed = parse_best_metrics(log_path)
        rec.update(parsed)
        row_map[name] = rec
        write_rows(out_csv, sort_rows_for_output(list(row_map.values())))

        print(
            f"[DONE] {name} train_status={rec['train_status']} "
            f"best={rec.get('best_mIoU', 'NA')} iter={rec.get('best_iter', 'NA')}"
        )

    print(f"[OK] comparison table written: {out_csv}")


if __name__ == "__main__":
    main()
