#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
MMSegTrain = ROOT / "third_party" / "mmsegmentation" / "tools" / "train.py"
BASE_CFG = ROOT / "configs" / "tp_dataset" / "segformer_b2_tp_skel_clDice_v2_4090_bs4.py"


def _active_cmdlines() -> List[str]:
    cmds: List[str] = []
    for d in os.listdir("/proc"):
        if not d.isdigit():
            continue
        p = Path("/proc") / d / "cmdline"
        try:
            cmd = p.read_bytes().replace(b"\x00", b" ").decode("utf-8", "ignore")
        except Exception:
            continue
        if cmd.strip():
            cmds.append(cmd)
    return cmds


def wait_for_pattern_done(pattern: str, poll_s: int = 30) -> None:
    print(f"[INFO] Waiting until no active process matches: {pattern}")
    while True:
        found = False
        for cmd in _active_cmdlines():
            if pattern in cmd:
                found = True
                break
        if not found:
            print("[INFO] Wait condition satisfied.")
            return
        time.sleep(poll_s)


def write_cfg(cfg_path: Path, work_dir: str, decode_cldice: float, aux_cldice: float) -> None:
    text = f"""_base_ = ['../segformer_b2_tp_skel_clDice_v2_4090_bs4.py']

# Auto-generated by tools/run_ablation_suite.py
work_dir = '{work_dir}'

model = dict(
    decode_head=dict(
        loss_decode=[
            dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            dict(type='DiceLoss', use_sigmoid=False, loss_weight=0.5),
            dict(type='SoftCLDiceLoss', foreground_index=1, iterations=10, loss_weight={decode_cldice}),
        ],
    ),
    auxiliary_head=dict(
        loss_bce=dict(type='CrossEntropyLoss', use_sigmoid=True, loss_weight=0.5),
        loss_dice=dict(type='DiceLoss', use_sigmoid=True, loss_weight=0.5),
        loss_cldice=dict(type='SoftCLDiceLoss', foreground_index=0, iterations=10, loss_weight={aux_cldice}),
    ),
)

default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        by_epoch=False,
        interval=500,
        save_last=True,
        max_keep_ckpts=20,
        save_best='mIoU',
        rule='greater',
        out_dir='{work_dir}/ckpt',
    ),
    logger=dict(type='LoggerHook', interval=50),
)

train_cfg = dict(type='IterBasedTrainLoop', max_iters=10000, val_interval=500)
"""
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(text, encoding="utf-8")


def parse_best_metrics(log_path: Path) -> Dict[str, str]:
    text = log_path.read_text(encoding="utf-8", errors="ignore")

    best_m = re.findall(r"best checkpoint with\s*([0-9.]+)\s*mIoU at\s*([0-9]+)\s*iter", text)
    if not best_m:
        return {"status": "no_best_found"}
    best_miou, best_iter = best_m[-1]

    best_marker = f"best checkpoint with {best_miou} mIoU at {best_iter} iter"
    marker_pos = text.rfind(best_marker)
    if marker_pos < 0:
        return {"status": "best_marker_not_found", "best_mIoU": best_miou, "best_iter": best_iter}

    val_pat = re.compile(
        r"Iter\(val\) \[281/281\]\s+aAcc:\s*([0-9.]+)\s+mIoU:\s*([0-9.]+)\s+mAcc:\s*([0-9.]+)\s+mDice:\s*([0-9.]+)\s+mFscore:\s*([0-9.]+)\s+mPrecision:\s*([0-9.]+)\s+mRecall:\s*([0-9.]+)",
        re.MULTILINE,
    )
    val_matches = list(val_pat.finditer(text[:marker_pos]))
    if not val_matches:
        return {"status": "val_summary_not_found", "best_mIoU": best_miou, "best_iter": best_iter}
    vm = val_matches[-1]
    aAcc, mIoU, mAcc, mDice, mFscore, mPrecision, mRecall = vm.groups()

    row_pat = re.compile(
        r"\|\s*tactile_paving\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|"
    )
    rows = list(row_pat.finditer(text[:marker_pos]))
    if not rows:
        return {"status": "tactile_row_not_found", "best_mIoU": best_miou, "best_iter": best_iter}
    tm = rows[-1]
    tactile_iou, tactile_acc, tactile_dice, tactile_fscore, tactile_precision, tactile_recall = tm.groups()

    return {
        "status": "ok",
        "best_iter": best_iter,
        "best_mIoU": best_miou,
        "aAcc": aAcc,
        "mIoU": mIoU,
        "mAcc": mAcc,
        "mDice": mDice,
        "mFscore": mFscore,
        "mPrecision": mPrecision,
        "mRecall": mRecall,
        "tactile_iou": tactile_iou,
        "tactile_acc": tactile_acc,
        "tactile_dice": tactile_dice,
        "tactile_fscore": tactile_fscore,
        "tactile_precision": tactile_precision,
        "tactile_recall": tactile_recall,
    }


def run_one(cfg: Path, work_dir: Path, log_path: Path, env: Dict[str, str]) -> int:
    work_dir.mkdir(parents=True, exist_ok=True)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "python",
        "-u",
        str(MMSegTrain),
        str(cfg),
        "--work-dir",
        str(work_dir),
    ]
    print(f"[RUN] {' '.join(cmd)}")
    with log_path.open("w", encoding="utf-8") as f:
        proc = subprocess.Popen(cmd, cwd=str(ROOT), env=env, stdout=f, stderr=subprocess.STDOUT)
        return proc.wait()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run TP ablation suite and record official metrics.")
    parser.add_argument("--wait-pattern", default="configs/tp_dataset/upernet_r50_tp_main_table1_B.py", help="Wait until matching running command disappears before starting.")
    parser.add_argument("--skip-wait", action="store_true")
    parser.add_argument("--group", choices=["all", "core", "weights"], default="all")
    parser.add_argument("--skip-train", action="store_true")
    parser.add_argument("--output-csv", default="work_dirs/ablation/ablation_results.csv")
    args = parser.parse_args()

    if not BASE_CFG.exists():
        raise FileNotFoundError(f"Missing base cfg: {BASE_CFG}")

    if not args.skip_wait and args.wait_pattern:
        wait_for_pattern_done(args.wait_pattern)

    cfg_dir = ROOT / "configs" / "tp_dataset" / "ablation_generated"
    log_dir = ROOT / "logs" / "ablation"
    out_csv = ROOT / args.output_csv
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    core_exps = [
        ("core_none", 0.0, 0.0),
        ("core_main_only", 0.1, 0.0),
        ("core_aux_only", 0.0, 0.1),
        ("core_both", 0.1, 0.1),
    ]
    weight_exps = [
        ("w_0p05", 0.05, 0.05),
        ("w_0p10", 0.10, 0.10),
        ("w_0p20", 0.20, 0.20),
        ("w_0p30", 0.30, 0.30),
    ]

    selected: List[Tuple[str, float, float]] = []
    if args.group in ("all", "core"):
        selected.extend(core_exps)
    if args.group in ("all", "weights"):
        selected.extend(weight_exps)

    env = os.environ.copy()
    env["PYTHONPATH"] = f"{ROOT}:{ROOT / 'third_party' / 'mmsegmentation'}:{env.get('PYTHONPATH', '')}"

    records: List[Dict[str, str]] = []
    for name, d_w, a_w in selected:
        cfg = cfg_dir / f"{name}.py"
        work_dir = ROOT / "work_dirs" / "ablation" / name
        log_path = log_dir / f"train_{name}_{time.strftime('%Y%m%d_%H%M%S')}.log"

        write_cfg(cfg, str(work_dir.relative_to(ROOT)), d_w, a_w)

        status = "skipped"
        exit_code = ""
        if not args.skip_train:
            rc = run_one(cfg, work_dir, log_path, env)
            status = "ok" if rc == 0 else "failed"
            exit_code = str(rc)

        best = parse_best_metrics(log_path) if log_path.exists() else {"status": "no_log"}

        rec: Dict[str, str] = {
            "name": name,
            "decode_cldice_weight": f"{d_w}",
            "aux_cldice_weight": f"{a_w}",
            "train_status": status,
            "exit_code": exit_code,
            "cfg": str(cfg.relative_to(ROOT)),
            "work_dir": str(work_dir.relative_to(ROOT)),
            "log": str(log_path.relative_to(ROOT)),
        }
        rec.update(best)
        records.append(rec)

        with out_csv.open("w", newline="", encoding="utf-8") as f:
            fieldnames = sorted({k for r in records for k in r.keys()})
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            for r in records:
                w.writerow(r)

        print(f"[DONE] {name} status={status} best={best.get('best_mIoU', 'NA')} iter={best.get('best_iter', 'NA')}")

    print(f"[OK] wrote summary: {out_csv}")


if __name__ == "__main__":
    main()
